In [6]:
import numpy as np

In [10]:
def rqi(a, initial_vec, tolerance = 10e-8):
    """
    Computes an eigenpair of A up to the given tolerance.
    """
    vec = initial_vec / np.linalg.norm(initial_vec)
    eye = np.eye(np.size(a,1))
    sigma = np.transpose(vec) @ a @ vec # @ is the matrix-vector or matrix-matrix multiplication operator
    
    iterations = 0
    
    while iterations <= 1000:
        vec = np.linalg.solve(a - sigma * eye, vec)
        vec /= np.linalg.norm(vec)
        sigma = np.transpose(vec) @ a @ vec
        iterations += 1
        print(a@v)
        print(sigma*v)
    return vec, sigma, iterations

def discrete_laplace_matrix(m):
    """
    Generates a matrix of the form
    m^2 * A, where the main diagonal of A contains 2s, and the
    elements directly above and below the main diagonal of A
    are -1. This is the matrix that arises when discretizing
    a Laplacian.
    """
    a = np.zeros((m-1,m-1))
    i,j = np.indices(a.shape)

    a[i==j] = 2.
    a[i==j-1] = -1.
    a[i==j+1] = -1.

    return m**2 * a

def eigvals_of_discrete_laplace(m, k):
    """
    Returns the kth eigenvalues of the matrix generated 
    by function discrete_laplace_matrix(m)
    """
    return 4 * m**2 *( np.sin( (k*np.pi)/(2*m)) )**2

def eigvecs_of_discrete_laplace(m, k):
    """
    Returns the normalised eigenvector corresponding to the kth
    eigenvalue of the matrix generated by function
    discrete_laplace_matrix(m) (eigenvectors lambda_1 to lambda_{m-1})
    """    
    vec = np.array([np.sin( (k*np.pi*j)/m ) for j in range(1,m)])
    return vec / np.linalg.norm(vec)

In [12]:
m = 5
a = discrete_laplace_matrix(m)

print(a)

v,w = np.linalg.eig(a)

print(w)

eigval = eigvals_of_discrete_laplace(m, 4)
eigvec = eigvecs_of_discrete_laplace(m, 4)

print("Analytic eigenvalues of A")
print(eigval)
print(eigvec)
print(np.linalg.norm(np.dot(a, eigvec) - eigval*eigvec))

vec, val, its = rqi(a, eigvec)
print(vec)
print(val)
print(its)

[[ 50. -25.   0.   0.]
 [-25.  50. -25.   0.]
 [  0. -25.  50. -25.]
 [  0.   0. -25.  50.]]
[[-0.37174803 -0.60150096 -0.37174803 -0.60150096]
 [ 0.60150096  0.37174803 -0.60150096 -0.37174803]
 [-0.60150096  0.37174803 -0.60150096  0.37174803]
 [ 0.37174803 -0.60150096 -0.37174803  0.60150096]]
Analytic eigenvalues of A
90.45084971874736
[ 0.37174803 -0.60150096  0.60150096 -0.37174803]
1.5888218580782548e-14
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.542

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.72875703 3125.        ]
[ 2886.27124297   772.54248594 -2022.54248594  1488.72875703]
[8181.35621484 5920.08497187  863.728757

In [61]:
res = np.zeros((m-1, m-1))
res[1,2] = 3